// <auto-generated />
using System;
using MagniFinance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagniFinance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220108180212_Teacher")]
    partial class Teacher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagniFinance.Models.College", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("college");
                });

            modelBuilder.Entity("MagniFinance.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Collegeid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Collegeid");

                    b.ToTable("course");
                });

            modelBuilder.Entity("MagniFinance.Models.Grades", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("grade")
                        .HasColumnType("real");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<int>("subjectid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("MagniFinance.Models.Students", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("grade")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("registration")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("MagniFinance.Models.Subjects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacherid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CoursesId");

                    b.HasIndex("teacherid");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("MagniFinance.Models.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("salary")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("teacher");
                });

            modelBuilder.Entity("StudentsSubjects", b =>
                {
                    b.Property<int>("studentsid")
                        .HasColumnType("int");

                    b.Property<int>("subjectsid")
                        .HasColumnType("int");

                    b.HasKey("studentsid", "subjectsid");

                    b.HasIndex("subjectsid");

                    b.ToTable("StudentsSubjects");
                });

            modelBuilder.Entity("MagniFinance.Models.Courses", b =>
                {
                    b.HasOne("MagniFinance.Models.College", null)
                        .WithMany("courses")
                        .HasForeignKey("Collegeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagniFinance.Models.Subjects", b =>
                {
                    b.HasOne("MagniFinance.Models.Courses", null)
                        .WithMany("subjects")
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagniFinance.Models.Teacher", "teacher")
                        .WithMany()
                        .HasForeignKey("teacherid");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("StudentsSubjects", b =>
                {
                    b.HasOne("MagniFinance.Models.Students", null)
                        .WithMany()
                        .HasForeignKey("studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagniFinance.Models.Subjects", null)
                        .WithMany()
                        .HasForeignKey("subjectsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagniFinance.Models.College", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("MagniFinance.Models.Courses", b =>
                {
                    b.Navigation("subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
